/**
 * Generated by the Croct CLI.
 *
 * Any manual changes will be overwritten.
 *
 * To regenerate, run `croct update`.
 */

/**
 * Content section
 * 
 * A section with content, bullets, CTA, and image.
 */
type Def$3523095b = {
  /**
   * Topics
   * 
   * A list of topics
   */
  'topics'?: Array<{
    /**
     * Tag
     * 
     * The tag to show alongside the title.
     */
    'tag'?: string,
    /**
     * Title
     */
    'title': string,
    /**
     * Description
     */
    'description': string,
  }>,
  /**
   * Buttons
   * 
   * The labels of the buttons.
   */
  'buttons': {
    /**
     * Reset
     * 
     * The label of the button that resets the variant.
     */
    'reset': string,
    /**
     * Track
     * 
     * The label of the button that tracks conversions.
     */
    'track': string,
  },
  /**
   * Heading
   * 
   * The main heading of the section.
   */
  'heading': string,
  /**
   * Variant
   * 
   * The variant to show.
   */
  'variant': {
    /**
     * Name
     * 
     * The name of the variant.
     */
    'name': string,
    /**
     * Color
     * 
     * The color of the variant.
     */
    'color': string,
  },
  /**
   * Pre-title
   * 
   * The pre-title of the section.
   */
  'preTitle'?: string,
  /**
   * Description
   * 
   * The description of the section.
   */
  'description'?: string,
};

declare module '@croct/plug/slot' {
  type DemoSection2V1 = Def$3523095b & {'_component': 'content-section@1' | null};
  
  export interface VersionedSlotMap {
    'demo-section': {
      latest: DemoSection2V1,
      '1': DemoSection2V1,
    };
  }
}

export {};
